# GitHub Actions Self-hosted Runner на Synology NAS

services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-actions-runner
    restart: unless-stopped
    
    environment:
      # Основные настройки GitHub
      REPO_URL: https://github.com/voovvaa/pavel
      ACCESS_TOKEN: "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"
      RUNNER_NAME: "synology-nas-runner"
      RUNNER_WORKDIR: "/tmp/runner/work"
      RUNNER_GROUP: "default"
      LABELS: "self-hosted,linux,synology,nas"
      
      # Автоматическое удаление при остановке
      EPHEMERAL: "true"
      
      # Дополнительные инструменты
      DOCKER_ENABLED: "true"
      
    volumes:
      # Docker socket для сборки образов
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Рабочая директория runner
      - runner-work:/tmp/runner/work
      
      # SSH ключи (если нужны)
      - ./ssh-keys:/home/runner/.ssh:ro
      
      # Временные файлы
      - runner-tmp:/tmp
    
    # Ресурсы (отключены для совместимости с Synology)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 2G
    #     reservations:
    #       cpus: '1.0' 
    #       memory: 1G
    
    # Логирование
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # Сеть
    networks:
      - runner-network
    
    # Метки
    labels:
      - "app=github-runner"
      - "project=geysandr-bot"

volumes:
  runner-work:
    driver: local
    name: github_runner_work
  runner-tmp:
    driver: local
    name: github_runner_tmp

networks:
  runner-network:
    driver: bridge
    name: github_runner_network