name: 📦 Chat History Import

on:
  push:
    paths:
      - 'chat/result.json'
      - 'chat/result_analysis.json'
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_retrain:
        description: 'Force complete retraining'
        required: false
        default: 'false'
        type: boolean

jobs:
  # Анализ чата локально
  analyze-chat:
    name: 🧠 Analyze Chat Data
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.force_retrain == 'true'
    outputs:
      has-analysis: ${{ steps.check.outputs.has-analysis }}
      patterns-count: ${{ steps.analyze.outputs.patterns-count }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check for chat data
        id: check
        run: |
          if [ -f "chat/result.json" ]; then
            FILE_SIZE=$(stat -c%s chat/result.json)
            echo "has-analysis=true" >> $GITHUB_OUTPUT
            echo "📊 Chat file found: $(($FILE_SIZE / 1024 / 1024)) MB"
          else
            echo "has-analysis=false" >> $GITHUB_OUTPUT
            echo "⚠️ No chat file found"
          fi

      - name: Analyze chat data
        id: analyze
        if: steps.check.outputs.has-analysis == 'true'
        run: |
          echo "🔍 Analyzing chat data..."
          bun run analyze chat/result.json
          
          if [ -f "chat/result_analysis.json" ]; then
            echo "✅ Analysis completed"
            
            # Extract patterns
            echo "🎭 Extracting personality patterns..."
            bun run patterns chat/result_analysis.json
            
            if [ -f "chat/result_personality.json" ]; then
              PATTERNS_COUNT=$(grep -o '"id"' chat/result_personality.json | wc -l)
              echo "patterns-count=$PATTERNS_COUNT" >> $GITHUB_OUTPUT
              echo "✅ Extracted $PATTERNS_COUNT personality patterns"
            else
              echo "patterns-count=0" >> $GITHUB_OUTPUT
              echo "⚠️ No personality patterns extracted"
            fi
          else
            echo "❌ Analysis failed"
            exit 1
          fi

      - name: Upload analysis artifacts
        if: steps.check.outputs.has-analysis == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: chat-analysis
          path: |
            chat/result_analysis.json
            chat/result_personality.json
          retention-days: 30

  # Импорт на NAS
  import-to-nas:
    name: 📤 Import to NAS
    runs-on: ubuntu-latest
    needs: analyze-chat
    if: always() && (needs.analyze-chat.outputs.has-analysis == 'true' || github.event_name == 'workflow_dispatch')
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download analysis artifacts
        if: needs.analyze-chat.outputs.has-analysis == 'true'
        uses: actions/download-artifact@v3
        with:
          name: chat-analysis
          path: chat/

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SYNOLOGY_SSH_KEY }}

      - name: Import chat history to NAS
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
        run: |
          echo "📦 Importing chat history to NAS..."
          
          # Create backup of current personality
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            if [ -f chat/result_personality.json ]; then
              cp chat/result_personality.json chat/result_personality.json.backup.$(date +%Y%m%d_%H%M%S)
              echo '✅ Backup of current personality created'
            fi
          "
          
          # Copy chat files to NAS
          if [ -f "chat/result.json" ]; then
            echo "📤 Copying chat data..."
            scp -o StrictHostKeyChecking=no chat/result.json $SYNOLOGY_USER@$SYNOLOGY_HOST:/volume1/docker/geysandr-bot/chat/
          fi
          
          if [ -f "chat/result_analysis.json" ]; then
            echo "📊 Copying analysis..."
            scp -o StrictHostKeyChecking=no chat/result_analysis.json $SYNOLOGY_USER@$SYNOLOGY_HOST:/volume1/docker/geysandr-bot/chat/
          fi
          
          if [ -f "chat/result_personality.json" ]; then
            echo "🎭 Copying personality..."
            scp -o StrictHostKeyChecking=no chat/result_personality.json $SYNOLOGY_USER@$SYNOLOGY_HOST:/volume1/docker/geysandr-bot/chat/
          fi

      - name: Restart bot with new personality
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
        run: |
          echo "🔄 Restarting bot with new personality..."
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            
            # Graceful restart if bot is running
            if docker compose ps | grep -q 'Up'; then
              echo '🔄 Restarting bot...'
              docker compose restart geysandr-bot
              
              # Wait for restart
              sleep 15
              
              # Health check
              docker compose exec -T geysandr-bot bun run health-check --quick || echo 'Health check warning after restart'
            else
              echo 'ℹ️ Bot not running, will use new personality on next start'
            fi
          "

  # Статистика и уведомления
  notify-import:
    name: 📢 Notify Import Status
    runs-on: ubuntu-latest
    needs: [analyze-chat, import-to-nas]
    if: always()
    steps:
      - name: Send import notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ALLOWED_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🧠 **Обновление личности Гейсандра Куловича**
            
            📊 **Результаты анализа:**
            • Статус: ${{ needs.analyze-chat.result == 'success' && '✅ Успешно' || '❌ Ошибка' }}
            • Паттернов извлечено: ${{ needs.analyze-chat.outputs.patterns-count || 'N/A' }}
            
            📤 **Импорт на NAS:**
            • Статус: ${{ needs.import-to-nas.result == 'success' && '✅ Успешно' || '❌ Ошибка' }}
            
            ${{ needs.import-to-nas.result == 'success' && '🤖 **Гейсандр Кулович перезапущен с новой личностью!**' || '' }}
            
            🔗 **Детали**: [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

  # Автоматическое создание PR с обновлениями (опционально)
  create-update-pr:
    name: 📝 Create Update PR
    runs-on: ubuntu-latest
    needs: [analyze-chat, import-to-nas]
    if: needs.analyze-chat.outputs.has-analysis == 'true' && needs.import-to-nas.result == 'success' && github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download analysis artifacts
        uses: actions/download-artifact@v3
        with:
          name: chat-analysis
          path: chat/

      - name: Create PR with updated personality
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: update bot personality with ${{ needs.analyze-chat.outputs.patterns-count }} patterns'
          title: '🧠 Обновление личности бота: ${{ needs.analyze-chat.outputs.patterns-count }} паттернов'
          body: |
            ## 🧠 Автоматическое обновление личности Гейсандра Куловича
            
            ### 📊 Статистика анализа:
            - **Паттернов извлечено**: ${{ needs.analyze-chat.outputs.patterns-count }}
            - **Дата анализа**: ${{ github.event.head_commit.timestamp }}
            - **Коммит источника**: ${{ github.sha }}
            
            ### 📁 Обновленные файлы:
            - `chat/result_analysis.json` - результаты анализа
            - `chat/result_personality.json` - извлеченные паттерны личности
            
            ### 🚀 Статус деплоя:
            - ✅ Импорт на NAS завершен
            - ✅ Бот перезапущен с новой личностью
            
            ### 🤖 Готово к работе!
            Гейсандр Кулович обновлен и готов к общению с улучшенной личностью.
            
            ---
            *Автоматически создано GitHub Actions*
          branch: update-personality-${{ github.run_number }}
          delete-branch: true