name: 🚀 Deploy Гейсандр Кулович

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      retrain:
        description: 'Force personality retraining'
        required: false
        default: 'false'
        type: boolean


jobs:
  # Этап 1: Тестирование и качество кода
  test:
    name: 🧪 Tests & Code Quality
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run type-check

      - name: Health check (без токенов)
        run: timeout 10s bun run health-check --quick || echo "Expected timeout - OK"

  # Этап 2: Деплой на Synology NAS (только для main branch)
  deploy:
    name: 🏠 Deploy to Synology NAS
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout deployment scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/
            docker-compose.yml
            .env.docker.example

      - name: Deploy to NAS (localhost)
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ALLOWED_CHAT_ID: ${{ secrets.ALLOWED_CHAT_ID }}
        run: |
          # Мы уже на NAS, используем localhost
          PROJECT_DIR="/volume1/docker/geysandr-bot"
          
          echo "🏠 Деплой на localhost (мы уже на NAS!)"
          
          # Создаем директории проекта
          mkdir -p "$PROJECT_DIR"
          mkdir -p "$PROJECT_DIR/chat"
          mkdir -p "$PROJECT_DIR/data"
          mkdir -p "$PROJECT_DIR/logs"
          
          # Копируем файлы проекта локально
          cp -r \
            Dockerfile \
            docker-compose.yml \
            package.json \
            bun.lockb \
            tsconfig.json \
            src/ \
            scripts/ \
            "$PROJECT_DIR/"
          
          # Копируем личность если есть
          if [ -f "chat/result_personality.json" ]; then
            cp chat/result_personality.json "$PROJECT_DIR/chat/"
          fi
          
          # Создаем .env.docker с секретами
          cat > "$PROJECT_DIR/.env.docker" << EOF
          TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
          OPENAI_API_KEY=$OPENAI_API_KEY
          ALLOWED_CHAT_ID=$ALLOWED_CHAT_ID
          OPENAI_MODEL=gpt-5-nano
          AI_MODE=hybrid
          AI_PROBABILITY=0.8
          DATABASE_PATH=/app/data/memory.db
          MEMORY_DAYS=30
          DEV_MODE=false
          NODE_ENV=production
          PERSONALITY_FILE=/app/chat/result_personality.json
          EOF
          
          # Выполняем деплой
          cd "$PROJECT_DIR"
          chmod +x scripts/*.sh
          
          echo "🐳 Собираем Docker образ..."
          docker build -t geysandr-bot:latest .
          
          echo "🚀 Запускаем деплой..."
          ./scripts/deploy.sh

  # Этап 4: Переобучение личности (опционально)
  retrain:
    name: 🧠 Retrain Personality
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.inputs.retrain == 'true' || contains(github.event.head_commit.message, '[retrain]')
    environment: production
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SYNOLOGY_SSH_KEY }}

      - name: Trigger retraining on NAS
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            
            # Проверяем есть ли новые данные чата
            if [ -f chat/result.json ]; then
              echo '🧠 Запускаем переобучение личности...'
              docker compose exec geysandr-bot bun run analyze /app/chat/result.json
              docker compose exec geysandr-bot bun run patterns /app/chat/result_analysis.json
              docker compose restart geysandr-bot
              echo '✅ Переобучение завершено'
            else
              echo '⚠️ Файл chat/result.json не найден'
            fi
          "

  # Этап 5: Уведомления
  notify:
    name: 📢 Notify Status
    runs-on: ubuntu-latest
    needs: [test, deploy]
    if: always()
    steps:
      - name: Get deployment status
        id: status
        run: |
          if [[ "${{ needs.test.result }}" == "success" && "${{ needs.deploy.result }}" == "success" ]]; then
            echo "status=✅ Успешно" >> $GITHUB_OUTPUT
            echo "color=good" >> $GITHUB_OUTPUT
          else
            echo "status=❌ Ошибка" >> $GITHUB_OUTPUT
            echo "color=danger" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ALLOWED_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🤖 **Гейсандр Кулович - Деплой ${{ steps.status.outputs.status }}**
            
            📋 **Детали:**
            • Коммит: `${{ github.sha }}`
            • Ветка: `${{ github.ref_name }}`
            • Автор: ${{ github.actor }}
            
            📊 **Статусы этапов:**
            • Тесты: ${{ needs.test.result == 'success' && '✅' || '❌' }}
            • Сборка: ✅ Локально на NAS
            • Деплой: ${{ needs.deploy.result == 'success' && '✅' || '❌' }}
            
            🔗 [Детали](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})