name: 🚀 Deploy Гейсандр Кулович

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      retrain:
        description: 'Force personality retraining'
        required: false
        default: 'false'
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Этап 1: Тестирование и качество кода
  test:
    name: 🧪 Tests & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run type-check

      - name: Health check (без токенов)
        run: timeout 10s bun run health-check --quick || echo "Expected timeout - OK"

  # Этап 2: Сборка Docker образа
  build:
    name: 🐳 Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # Этап 3: Деплой на Synology NAS (только для main branch)
  deploy:
    name: 🏠 Deploy to Synology NAS
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout deployment scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/
            docker-compose.yml
            .env.docker.example

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SYNOLOGY_SSH_KEY }}

      - name: Deploy to Synology NAS
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ALLOWED_CHAT_ID: ${{ secrets.ALLOWED_CHAT_ID }}
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        run: |
          # Создаем директорию проекта на NAS
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            mkdir -p /volume1/docker/geysandr-bot
          "
          
          # Копируем файлы деплоя
          scp -o StrictHostKeyChecking=no docker-compose.yml $SYNOLOGY_USER@$SYNOLOGY_HOST:/volume1/docker/geysandr-bot/
          scp -o StrictHostKeyChecking=no -r scripts/ $SYNOLOGY_USER@$SYNOLOGY_HOST:/volume1/docker/geysandr-bot/
          
          # Создаем .env.docker на NAS
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            cat > .env.docker << EOF
          TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
          OPENAI_API_KEY=$OPENAI_API_KEY
          ALLOWED_CHAT_ID=$ALLOWED_CHAT_ID
          OPENAI_MODEL=gpt-5-nano
          AI_MODE=hybrid
          AI_PROBABILITY=0.8
          DATABASE_PATH=/app/data/memory.db
          MEMORY_DAYS=30
          DEV_MODE=false
          NODE_ENV=production
          PERSONALITY_FILE=/app/chat/result_personality.json
          EOF
          "
          
          # Обновляем docker-compose.yml с правильным образом
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            sed -i 's|build:|# build:|' docker-compose.yml
            sed -i 's|context: \.|# context: \.|' docker-compose.yml
            sed -i 's|dockerfile: Dockerfile|# dockerfile: Dockerfile|' docker-compose.yml
            sed -i '/# build:/a \ \ \ \ image: $IMAGE_TAG' docker-compose.yml
          "
          
          # Выполняем деплой
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            chmod +x scripts/*.sh
            
            # Пуллим новый образ
            docker pull $IMAGE_TAG
            
            # Запускаем деплой скрипт
            ./scripts/deploy.sh
          "

  # Этап 4: Переобучение личности (опционально)
  retrain:
    name: 🧠 Retrain Personality
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event.inputs.retrain == 'true' || contains(github.event.head_commit.message, '[retrain]')
    environment: production
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SYNOLOGY_SSH_KEY }}

      - name: Trigger retraining on NAS
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            
            # Проверяем есть ли новые данные чата
            if [ -f chat/result.json ]; then
              echo '🧠 Запускаем переобучение личности...'
              docker compose exec geysandr-bot bun run analyze /app/chat/result.json
              docker compose exec geysandr-bot bun run patterns /app/chat/result_analysis.json
              docker compose restart geysandr-bot
              echo '✅ Переобучение завершено'
            else
              echo '⚠️ Файл chat/result.json не найден'
            fi
          "

  # Этап 5: Уведомления
  notify:
    name: 📢 Notify Status
    runs-on: ubuntu-latest
    needs: [test, build, deploy]
    if: always()
    steps:
      - name: Get deployment status
        id: status
        run: |
          if [[ "${{ needs.test.result }}" == "success" && "${{ needs.build.result }}" == "success" && "${{ needs.deploy.result }}" == "success" ]]; then
            echo "status=✅ Успешно" >> $GITHUB_OUTPUT
            echo "color=good" >> $GITHUB_OUTPUT
          else
            echo "status=❌ Ошибка" >> $GITHUB_OUTPUT
            echo "color=danger" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ALLOWED_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🤖 **Гейсандр Кулович - Деплой ${{ steps.status.outputs.status }}**
            
            📋 **Детали:**
            • Коммит: `${{ github.sha }}`
            • Ветка: `${{ github.ref_name }}`
            • Автор: ${{ github.actor }}
            
            📊 **Статусы этапов:**
            • Тесты: ${{ needs.test.result == 'success' && '✅' || '❌' }}
            • Сборка: ${{ needs.build.result == 'success' && '✅' || '❌' }}
            • Деплой: ${{ needs.deploy.result == 'success' && '✅' || '❌' }}
            
            🔗 [Детали](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})