name: 📦 Release Management

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

jobs:
  # Создание релиза
  create-release:
    name: 🏷️ Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Generate changelog
        id: changelog
        run: |
          # Получаем последний тег для сравнения
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [[ -n "$LAST_TAG" ]]; then
            echo "Generating changelog from $LAST_TAG to HEAD"
            CHANGELOG=$(git log --pretty=format:"- %s" $LAST_TAG..HEAD)
          else
            echo "No previous tag found, using last 10 commits"
            CHANGELOG=$(git log --pretty=format:"- %s" -n 10)
          fi
          
          # Экранируем для GitHub
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: 🤖 Гейсандр Кулович ${{ steps.version.outputs.version }}
          body: |
            ## 🎉 Новая версия Гейсандра Куловича!
            
            ### 📋 Что нового:
            ${{ steps.changelog.outputs.changelog }}
            
            ### 🚀 Установка:
            ```bash
            # Клонировать репозиторий
            git clone https://github.com/${{ github.repository }}.git
            cd geysandr-bot
            
            # Запустить деплой
            ./scripts/deploy.sh
            ```
            
            ### 🐳 Docker Image:
            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
            ```
            
            ### 📊 Статистика проекта:
            - TypeScript код с полной типизацией
            - Docker образ размером ~211MB (Alpine)  
            - Multi-stage сборка с кэшированием
            - Автоматические тесты и health checks
            - CI/CD pipeline с уведомлениями
            
            ### 🔧 Конфигурация:
            Смотри [DOCKER.md](./DOCKER.md) для подробной настройки
          draft: false
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}

  # Сборка и публикация Docker образа с тегом релиза
  build-release:
    name: 🐳 Build Release Image
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.create-release.outputs.version }}
            ghcr.io/${{ github.repository }}:stable
          labels: |
            org.opencontainers.image.title=Гейсандр Кулович Bot
            org.opencontainers.image.description=Advanced Telegram AI Bot with emotional intelligence
            org.opencontainers.image.version=${{ needs.create-release.outputs.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # Автоматический деплой релиза (опционально)
  deploy-release:
    name: 🚀 Deploy Release
    runs-on: ubuntu-latest
    needs: [create-release, build-release]
    if: github.event.inputs.prerelease != 'true'
    environment: production
    steps:
      - name: Checkout deployment files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/
            docker-compose.yml

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SYNOLOGY_SSH_KEY }}

      - name: Deploy release to production
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USER: ${{ secrets.SYNOLOGY_USER }}
          RELEASE_TAG: ${{ needs.create-release.outputs.version }}
        run: |
          # Обновляем на NAS на релизную версию
          ssh -o StrictHostKeyChecking=no $SYNOLOGY_USER@$SYNOLOGY_HOST "
            cd /volume1/docker/geysandr-bot
            
            echo '🚀 Деплой релиза $RELEASE_TAG...'
            
            # Обновляем docker-compose.yml на релизную версию
            sed -i 's|ghcr.io/.*/geysandr-bot:.*|ghcr.io/${{ github.repository }}:$RELEASE_TAG|' docker-compose.yml
            
            # Создаем бэкап
            ./scripts/backup.sh
            
            # Деплоим релиз
            docker pull ghcr.io/${{ github.repository }}:$RELEASE_TAG
            docker compose up -d --force-recreate
            
            # Проверяем здоровье после деплоя
            sleep 30
            docker compose exec -T geysandr-bot bun run health-check --quick || echo 'Warning: Health check failed'
            
            echo '✅ Релиз $RELEASE_TAG развернут'
          "

  # Уведомление о релизе
  notify-release:
    name: 📢 Release Notification
    runs-on: ubuntu-latest
    needs: [create-release, build-release, deploy-release]
    if: always()
    steps:
      - name: Send release notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ALLOWED_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🎉 **Новый релиз Гейсандра Куловича!**
            
            📦 **Версия**: `${{ needs.create-release.outputs.version }}`
            🏷️ **Тип**: ${{ github.event.inputs.prerelease == 'true' && 'Pre-release' || 'Stable Release' }}
            
            📊 **Статус развертывания**:
            • Сборка: ${{ needs.build-release.result == 'success' && '✅' || '❌' }}
            • Деплой: ${{ needs.deploy-release.result == 'success' && '✅' || needs.deploy-release.result == 'skipped' && '⏭️ Пропущен' || '❌' }}
            
            🐳 **Docker Image**: 
            `ghcr.io/${{ github.repository }}:${{ needs.create-release.outputs.version }}`
            
            🔗 **Детали**: [GitHub Release](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.create-release.outputs.version }})
            
            ${{ needs.deploy-release.result == 'success' && '🚀 **Гейсандр Кулович обновлен и готов к работе!**' || '' }}